//hacker news
define_webjump("hackernews", "https://news.ycombinator.com/news");

//shaarli bookmark
define_webjump("shaarli","javascript:location.href='https://shaarli.0xcb0.com/?post=' + encodeURIComponent(window.location)+'&title=' + encodeURIComponent(document.title)+'&source=bookmarklet'");

//from http://www.tobez.org/download/readability.html
define_webjump("readability", "javascript:(function(){readStyle='style-athelas';readSize='size-large';readMargin='margin-medium';_readability_script=document.createElement('SCRIPT');_readability_script.type='text/javascript';_readability_script.src='http://www.tobez.org/download/old-readability.js?x='+(Math.random());document.getElementsByTagName('head')[0].appendChild(_readability_script);_readability_css=document.createElement('LINK');_readability_css.rel='stylesheet';_readability_css.href='http://www.tobez.org/download/old-readability.css';_readability_css.type='text/css';_readability_css.media='all';document.getElementsByTagName('head')[0].appendChild(_readability_css);_readability_print_css=document.createElement('LINK');_readability_print_css.rel='stylesheet';_readability_print_css.href='http://www.tobez.org/download/old-readability-print.css';_readability_print_css.media='print';_readability_print_css.type='text/css';document.getElementsByTagName('head')[0].appendChild(_readability_print_css);})();");

define_webjump("q", "javascript:(function(){function%20loadScript()%7Bif(console%20%26%26%20typeof(console.log)===%27function%27)%7Bconsole.log(%27SpritzletInit%20v1.1.8%20-%20Loading%20https://sdk.spritzinc.com/bookmarklet/latest/js/SpritzletOuter.js%27);}var%20script=document.createElement(%27script%27);script.setAttribute(%27type%27,%27text/javascript%27);script.setAttribute(%27charset%27,%27UTF-8%27);script.setAttribute(%27async%27,%27true%27);script.setAttribute(%27src%27,%27https://sdk.spritzinc.com/bookmarklet/latest/js/SpritzletOuter.js%3F%27+(new%20Date().getTime()).toString().substring(0,7));document.documentElement.appendChild(script);setTimeout(function()%7Bif(Spritzlet.timedOut===true)%7Balert(%22Sorry,%20it%20looks%20like%20this%20site%20doesn%27t%20allow%20bookmarklets%20to%20be%20run%20or%20Spritz%20servers%20aren%27t%20responding.%22);}},3000);script.onload=function()%7BSpritzlet.timedOut=false;var%20rs=script.readyState;if(!rs%20||%20rs===%27loaded%27%20||%20rs===%27complete%27)%7Bscript.onload=script.onreadystatechange=null;Spritzlet.init();}};}if(window.Spritzlet)%7BSpritzlet.activate();}else%7Bwindow.Spritzlet=window.Spritzlet%20||%7B};window.Spritzlet=%7Borigin:window.location.protocol+%27//%27+window.location.host,loaderVersion:1.1,timedOut:true};loadScript();}})();");
